### PR TITLE
Add support for XNU 22

### PR DESCRIPTION
**Pull request by xliuxu**
Add headers for XNU22.
The `sysreg_offsets` has not been changed so I did not create a new one.
 
Verified on UTM 4.4.4 on iPad Pro 2021 16.1.1

### CODE REVIEW

**Comment by SoY0ung** [comment]
Hello, may I kindly request your assistance in providing UTM-HV package that support XNU22? I have been attempting to compile using GitHub Actions, but regrettably, I have not achieved success thus far :(
Your guidance would be greatly appreciated. Thank you!

**Comment by xliuxu** [comment]
> Hello, may I kindly request your assistance in providing UTM-HV package that support XNU22? I have been attempting to compile using GitHub Actions, but regrettably, I have not achieved success thus far :( Your guidance would be greatly appreciated. Thank you!

You can compile the Hypervisor framework locally and replace the one in UTM.ipa
```
xcodebuild archive -archivePath "Hypervisor" -scheme "Hypervisor" -sdk iphoneos -configuration Release 
```
Then unzip the UTM ipa, replace the Hypervisor.framework under `UTM.app/Frameworks/` with the one you built in 
Hypervisor.xcarchive/Products/Library/Frameworks/Hypervisor.framework, repack and install it. Have fun :)

**Comment by harshit181** [comment]
> > Hello, may I kindly request your assistance in providing UTM-HV package that support XNU22? I have been attempting to compile using GitHub Actions, but regrettably, I have not achieved success thus far :( Your guidance would be greatly appreciated. Thank you!
> 
> You can compile the Hypervisor framework locally and replace the one in UTM.ipa
> 
> ```
> xcodebuild archive -archivePath "Hypervisor" -scheme "Hypervisor" -sdk iphoneos -configuration Release 
> ```
> 
> Then unzip the UTM ipa, replace the Hypervisor.framework under `UTM.app/Frameworks/` with the one you built in Hypervisor.xcarchive/Products/Library/Frameworks/Hypervisor.framework, repack and install it. Have fun :)
Crashing for me on M1 ipad -16.1

**Comment by drprince87** [comment]
Please help me guys
I don’t have neither mac or xcode 
Can anyone release the edited file utm hv version that work on trollstore 2 
Help me please 🙏🙏🙏🙏

**Comment by drprince87** [comment]
> Hello, may I kindly request your assistance in providing UTM-HV package that support XNU22? I have been attempting to compile using GitHub Actions, but regrettably, I have not achieved success thus far :(
> Your guidance would be greatly appreciated. Thank you!

Me too 🙏🙏🙏🙏🙏

**Comment by SoY0ung** [comment]
> Please help me guys
> I don’t have neither mac or xcode
> Can anyone release the edited file utm hv version that work on trollstore 2
> Help me please 🙏🙏🙏🙏

I upload the modified UTM ipa [here](https://github.com/SoY0ung/UTM/releases/tag/v4.4.4(hv)).

**Comment by drprince87** [comment]
> > Please help me guys
> > I don’t have neither mac or xcode
> > Can anyone release the edited file utm hv version that work on trollstore 2
> > Help me please 🙏🙏🙏🙏
> 
> I upload the modified UTM ipa [here](https://github.com/SoY0ung/UTM/releases/tag/v4.4.4(hv)).

Thanks sir 🫡

**Comment by NumberVII** [comment]
> > Please help me guys
> > I don’t have neither mac or xcode
> > Can anyone release the edited file utm hv version that work on trollstore 2
> > Help me please 🙏🙏🙏🙏
> 
> I upload the modified UTM ipa [here](https://github.com/SoY0ung/UTM/releases/tag/v4.4.4(hv)).

Installed using TrollStore2, crashes when launching.
iPad Pro M1 8GB iPadOS 16.3, anyone get any luck?

**Comment by watermelonoof** [comment]
> > > Please help me guys
> > > I don’t have neither mac or xcode
> > > Can anyone release the edited file utm hv version that work on trollstore 2
> > > Help me please 🙏🙏🙏🙏
> > 
> > 
> > I upload the modified UTM ipa [here](https://github.com/SoY0ung/UTM/releases/tag/v4.4.4(hv)).
> 
> Installed using TrollStore2, crashes when launching. iPad Pro M1 8GB iPadOS 16.3, anyone get any luck?

Works on my iPad Air 5 M1, 8GB, iPadOS 16.3
There are random crashes though (not sure if relevant)

**Pull request merged**
